AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: S3 Reference Architecture: Private encrypted bucket
  using AES256 with retention on object deletion. (fdp-1oc5gsre6)'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: S3 Bucket Policy Configuration
        Parameters:
          - S3UserARNs
Parameters:
  S3UserARNs:
    Type: CommaDelimitedList
    Default: ""
    Description: (Optional) User ARNs allowed to access S3 Bucket
    ConstraintDescription: List of ARNs separated by commas (i.e. arn:aws:iam::011223344556:user/jsmith,arn:aws:iam::544332211006:user/rjones)
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: SC-S3-RA-S3-Bucket
  S3BucketTagger:
    Type: Custom::S3BucketTagger
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-bucket-tagger-FunctionArn'
      BucketName: !Ref S3Bucket
  S3BucketPolicy:
    Type: Custom::SCS3BucketPolicy
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-sc-bucket-policy-test-FunctionArn'
      BucketName: !Ref S3Bucket
      ExtraPrincipals: !Ref S3UserARNs
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
  BucketARN:
    Value: !GetAtt 'S3Bucket.Arn'
  BucketUrl:
    Value: !Sub 'https://console.aws.amazon.com/s3/home?region=${AWS::Region}&bucket=${S3Bucket}'
